# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Documents/Code/SoC_Lab/SingleCycle/cpuIO/project_1/project_1.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/Code/SoC_Lab/SingleCycle/cpuIO/project_1/project_1.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Documents/Code/SoC_Lab/SingleCycle/cpuIO/project_1/project_1.srcs/sources_1/ip/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/Code/SoC_Lab/SingleCycle/cpuIO/project_1/project_1.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
