# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/dram/dram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dram || ORIG_REF_NAME==dram} -quiet] -quiet
