# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lenovo/Downloads/22_6_28_CPU_Project/CPU_Project/CPU_Project.srcs/sources_1/ip/dram/dram.xci
# IP: The module: 'dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Downloads/22_6_28_CPU_Project/CPU_Project/CPU_Project.srcs/sources_1/ip/dram/dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/lenovo/Downloads/22_6_28_CPU_Project/CPU_Project/CPU_Project.srcs/sources_1/ip/dram/dram.xci
# IP: The module: 'dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lenovo/Downloads/22_6_28_CPU_Project/CPU_Project/CPU_Project.srcs/sources_1/ip/dram/dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
